"""B6 — Data written by v0.7.1 must stay readable: the frozen ``legacy_home_v0_7_1`` home.

The fixture was produced by the v0.7.1 backend (see ``fixtures/build_legacy_home.py``) and
is never regenerated by later code. Rebuildable caches are absent, so these tests also pin
that the session index, timeline index and timing store are rebuilt from the
authoritative files.
"""

from __future__ import annotations

import json
import shutil
import sqlite3
import sys
from contextlib import closing
from pathlib import Path
from typing import Any

import pytest

from .support.backend import Backend
from .support.fake_llm import FakeLLM
from .support.golden import assert_golden
from .support.home import FAKE_ACP_AGENT, CleoHome
from .support.views import index_rows, session_files

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "legacy_home_v0_7_1"


def _fixture_thread(space: str, project: str) -> str:
    (manifest,) = (FIXTURE / "memory" / space / "projects" / project / "sessions").glob(
        "*/manifest.json")
    return manifest.parent.name


CHAT_ID = _fixture_thread("non_productivity", "general")
RESEARCH_ID = _fixture_thread("non_productivity", "research")
TASK_ID = _fixture_thread("productivity", "workspace")


@pytest.fixture
def legacy_home(cleo_home: CleoHome, fake_llm: FakeLLM) -> CleoHome:
    home = cleo_home  # Fresh Git workspace and user home; the data home is replaced.
    shutil.rmtree(home.home)
    research = home.root / "research"
    research.mkdir()
    tokens = {
        "{{HOME}}": str(home.home), "{{WORKSPACE}}": str(home.workspace),
        "{{USER}}": str(home.user_home), "{{LLM_URL}}": fake_llm.base_url,
        "{{FAKE_ACP_AGENT}}": str(FAKE_ACP_AGENT), "{{PYTHON}}": sys.executable,
        "{{RESEARCH}}": str(research),
    }
    for source in FIXTURE.rglob("*"):
        if not source.is_file():
            continue
        target = home.home / source.relative_to(FIXTURE)
        target.parent.mkdir(parents=True, exist_ok=True)
        if source.suffix == ".sql":
            script = source.read_text(encoding="utf-8")
            for token, value in tokens.items():
                script = script.replace(token, value)
            with closing(sqlite3.connect(target.with_suffix(""))) as connection:
                connection.executescript(script)
        elif source.suffix in {".json", ".jsonl", ".md"}:
            text = source.read_text(encoding="utf-8")
            for token, value in tokens.items():
                text = text.replace(token, value if source.suffix == ".md"
                                    else json.dumps(value)[1:-1])
            target.write_text(text, encoding="utf-8", newline="\n")
        else:
            shutil.copyfile(source, target)
    return home


@pytest.fixture
def legacy_replacements(legacy_home: CleoHome, replacements: dict) -> dict:
    values = dict(replacements)
    values[str(legacy_home.root / "research")] = "<RESEARCH>"
    return values


@pytest.fixture
def legacy_backend(legacy_home: CleoHome):
    process = Backend(legacy_home).start()
    try:
        yield process
    finally:
        process.kill()


def _thread_view(thread: dict[str, Any]) -> dict[str, Any]:
    # Timing comes from a rebuildable store that the fixture deliberately omits.
    return {key: value for key, value in thread.items() if key not in {"currentTiming"}}


def test_legacy_workspace_threads_and_memory_load_unchanged(
    legacy_backend: Backend, legacy_home: CleoHome, legacy_replacements: dict,
) -> None:
    workspace = legacy_backend.call("load_workspace")
    assert_golden("legacy/workspace", {
        "workspace": {**workspace, "threads": [_thread_view(t) for t in workspace["threads"]]},
        "threads": {
            name: _thread_view(legacy_backend.call("load_thread", thread_id=thread_id,
                                                   activate=False))
            for name, thread_id in (("chat", CHAT_ID), ("research", RESEARCH_ID),
                                    ("task", TASK_ID))
        },
        "index": index_rows(legacy_home),
    }, legacy_replacements)


def test_missing_session_index_is_rebuilt_from_the_manifests(
    legacy_home: CleoHome, legacy_replacements: dict,
) -> None:
    """Q5 (fixed in S9): a missing index is rebuilt when the backend opens the store."""
    (legacy_home.memory / "sessions.sqlite3").unlink()
    backend = Backend(legacy_home).start()
    try:
        before = backend.call("load_workspace")
        backend.call("load_thread", thread_id=CHAT_ID, activate=False)
        after = backend.call("load_workspace")
    finally:
        backend.kill()
    assert_golden("legacy/missing_index", {
        "threads_before_opening": [thread["id"] for thread in before["threads"]],
        "threads_after_opening_one": sorted(thread["id"] for thread in after["threads"]),
        "index_after": [row["id"] for row in index_rows(legacy_home)],
    }, legacy_replacements)


def test_legacy_timeline_paging(legacy_backend: Backend, legacy_replacements: dict) -> None:
    first = legacy_backend.call("load_timeline", thread_id=TASK_ID, limit=3)
    older = legacy_backend.call("load_timeline", thread_id=TASK_ID, limit=3,
                                cursor=first["before"], direction="before")
    newer = legacy_backend.call("load_timeline", thread_id=TASK_ID, limit=3,
                                cursor=older["after"], direction="after")
    long_item = next(item for item in first["items"] + older["items"] + newer["items"]
                     if item["type"] == "message")
    content = legacy_backend.call("read_timeline_content", thread_id=TASK_ID,
                                  item_id=long_item["id"], field="content")
    assert_golden("legacy/timeline_paging", {
        "latest": first, "before": older, "after": newer, "content": content,
    }, legacy_replacements)


def test_continuing_a_legacy_chat_replays_only_active_history(
    legacy_backend: Backend, legacy_home: CleoHome, fake_llm: FakeLLM,
    legacy_replacements: dict,
) -> None:
    legacy_backend.run_turn(CHAT_ID, "What is on Saturday?")
    request = fake_llm.chat_requests()[-1]
    files = session_files(legacy_home, {"id": CHAT_ID, "space": "non_productivity",
                                        "project": "general"})
    assert_golden("legacy/continue_chat", {
        "messages_sent": [
            {"role": message["role"], "content": message.get("content")}
            for message in request["messages"] if message["role"] != "system"
        ],
        "appended_events": [
            {key: event.get(key) for key in ("seq", "type", "actor", "content")}
            for event in files["events.jsonl"][-3:]
        ],
        "manifest": files["manifest.json"],
    }, legacy_replacements)


def test_continuing_a_legacy_task_resumes_its_native_session(
    legacy_backend: Backend, legacy_home: CleoHome, legacy_replacements: dict,
) -> None:
    stream = legacy_backend.stream_turn(TASK_ID, "One more change")
    stream.result()
    files = session_files(legacy_home, {"id": TASK_ID, "space": "productivity",
                                        "project": "workspace"})
    assert_golden("legacy/continue_task", {
        "event_types": [event["type"] for event in stream.events
                        if event["type"] != "timing"],
        "manifest": files["manifest.json"],
    }, legacy_replacements)


def test_legacy_memory_review_state(legacy_backend: Backend, legacy_replacements: dict) -> None:
    memory = legacy_backend.call("load_memory")
    assert_golden("legacy/memory", memory, legacy_replacements)
