import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
import { chromium } from "playwright";

const ui = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const scratch = await mkdtemp(join(tmpdir(), "cleo-evolution-overview-"));
const server = await createServer({ root: ui, cacheDir: join(scratch, "vite"), server: { host: "127.0.0.1", port: 0 },
  plugins: [{ name: "overview-fixture", configureServer(server) {
    server.middlewares.use("/__overview", async (_request, response) => {
      response.setHeader("Content-Type", "text/html; charset=utf-8");
      response.end(await server.transformIndexHtml("/__overview", '<div id="root"></div><script type="module" src="/tests/fixtures/evolution-overview.tsx"></script>'));
    });
  } }] });
let browser;
try {
  await server.listen();
  browser = await chromium.launch({ executablePath: process.env.CLEO_TEST_BROWSER, headless: true });
  const page = await browser.newPage({ viewport: { width: 1080, height: 900 } });
  page.setDefaultTimeout(7000);
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(`${server.resolvedUrls.local[0]}__overview`);
  await page.getByRole("button", { name: "新建 PR", exact: true }).and(page.locator(":enabled")).waitFor();
  assert.equal(await page.locator(".evolution-github").count(), 0);
  assert.equal(await page.locator(".evolution-actions button").count(), 0);
  await page.getByRole("button", { name: "新建 PR", exact: true }).click();
  const form = page.getByRole("region", { name: "贡献提交" });
  const target = form.getByLabel("目标分支", { exact: true });
  await target.and(page.locator(":enabled")).waitFor();
  assert.equal(await target.locator('option[value="main"]').count(), 0);
  assert.equal(await page.getByRole("button", { name: /刷新目标分支|检查分支是否|检查兼容性/ }).count(), 0);
  await target.selectOption("accept-existing");
  await form.getByLabel("PR 标题", { exact: true }).fill("保留这个标题");
  await form.getByLabel("PR 说明", { exact: true }).fill("保留这段说明");
  await form.getByText("可以向此分支提交", { exact: true }).waitFor();
  await page.evaluate(() => { window.evolutionUI.branches = []; window.evolutionUI.offset += 60001; window.dispatchEvent(new Event("focus")); });
  await target.locator('option[value="accept-existing"]').filter({ hasText: "不可用" }).waitFor({ state: "attached" });
  assert.equal(await target.inputValue(), "accept-existing");
  assert.equal(await form.getByRole("button", { name: "创建新 PR", exact: true }).isDisabled(), true);
  await page.evaluate(() => { window.evolutionUI.branches = ["accept-existing"]; window.evolutionUI.offset += 60001; window.dispatchEvent(new Event("focus")); });
  await page.waitForFunction(() => document.querySelector('select[aria-label="目标分支"] option[value="accept-existing"]')?.disabled === false);
  await page.evaluate(() => { window.evolutionUI.failCatalog = true; window.evolutionUI.offset += 60001; window.dispatchEvent(new Event("focus")); });
  const readError = form.getByRole("alert").filter({ hasText: "无法读取分支（测试）" });
  await readError.waitFor();
  assert.equal(await form.getByLabel("PR 标题", { exact: true }).inputValue(), "保留这个标题");
  assert.equal(await target.inputValue(), "accept-existing");
  await page.evaluate(() => { window.evolutionUI.failCatalog = false; });
  await readError.getByRole("button", { name: "重试", exact: true }).click();
  await readError.waitFor({ state: "hidden" });
  await form.getByLabel("提交方式", { exact: true }).selectOption("request");
  await form.getByLabel("申请分支名称", { exact: true }).fill("my-request-draft");
  await page.evaluate(() => { window.evolutionUI.branches.push("waiting"); window.evolutionUI.offset += 60001; window.dispatchEvent(new Event("focus")); });
  await form.getByText("分支已就绪", { exact: true }).waitFor();
  assert.equal(await form.getByLabel("申请分支名称", { exact: true }).inputValue(), "my-request-draft");
  const beforeHidden = await page.evaluate(() => window.evolutionUI.reads.length);
  await page.evaluate(() => { Object.defineProperty(document, "hidden", { configurable: true, value: true }); window.evolutionUI.offset += 60001; window.dispatchEvent(new Event("focus")); });
  assert.equal(await page.evaluate(() => window.evolutionUI.reads.length), beforeHidden);
  await page.evaluate(() => { delete document.hidden; document.dispatchEvent(new Event("visibilitychange")); });
  assert.equal(await page.evaluate(() => window.evolutionUI.writes.length), 0);
  await form.getByRole("button", { name: "向该分支提交 PR", exact: true }).click();
  await form.getByLabel("PR 标题", { exact: true }).fill("提交当前改进");
  await form.getByRole("button", { name: "创建新 PR", exact: true }).click();
  await form.getByRole("alert").filter({ hasText: "提交网络失败（测试）" }).waitFor();
  assert.equal(await form.getByLabel("PR 标题", { exact: true }).inputValue(), "提交当前改进");
  await form.getByRole("button", { name: "创建新 PR", exact: true }).click();
  await page.getByRole("status", { name: "PR 提交结果" }).waitFor();
  const writes = await page.evaluate(() => window.evolutionUI.writes);
  assert.equal(writes.length, 2);
  assert.equal(writes[0].params.submissionId, writes[1].params.submissionId);
  await page.getByRole("button", { name: "查看状态", exact: true }).click();
  await page.waitForFunction(() => window.evolutionUI.reads.filter(action => action === "mergeAssistance").length === 2 && window.evolutionUI.activeReads === 0);
  assert.equal(await page.evaluate(() => window.evolutionUI.maxReads), 1, "Read-only panels must not race the backend operation lock");
  assert.equal(await page.getByRole("button", { name: /^刷新 PR/ }).count(), 0);
  await page.getByRole("button", { name: "关闭", exact: true }).click();
  await page.getByRole("button", { name: "选择版本", exact: true }).click();
  await page.waitForFunction(() => window.evolutionUI.reads.includes("releases") && window.evolutionUI.activeReads === 0);
  assert.equal(await page.getByRole("button", { name: "检查发布版本", exact: true }).count(), 0);
  await page.getByText("查找发布版本", { exact: true }).click();
  assert.match(await page.getByLabel("发布版本", { exact: true }).innerText(), /v0.4.9/);
  await page.getByRole("button", { name: "关闭", exact: true }).click();
  await page.getByRole("button", { name: "其他任务运行（测试）", exact: true }).click();
  await page.getByText("其他任务正在运行", { exact: true }).waitFor();
  assert.equal(await page.locator(".evolution-spin").count(), 0);
  assert.equal(await page.getByText("正在修改…", { exact: true }).count(), 0);
  await page.getByRole("button", { name: "其他任务运行（测试）", exact: true }).click();
  await page.getByRole("button", { name: "断开账号（测试）", exact: true }).click();
  assert.equal(await page.getByRole("region", { name: "GitHub 登录" }).count(), 0);
  await page.getByRole("button", { name: "新建 PR", exact: true }).click();
  await page.getByRole("button", { name: "连接 GitHub", exact: true }).click();
  await page.getByLabel("GitHub 一次性验证码", { exact: true }).getByText("TEST-CODE", { exact: true }).waitFor();
  await page.getByRole("button", { name: "关闭", exact: true }).click();
  await page.getByText("等待 GitHub 授权", { exact: true }).waitFor();
  assert.equal(await page.locator(".evolution-spin").count(), 0);
  await page.getByRole("button", { name: "继续连接 GitHub", exact: true }).click();
  await page.getByLabel("GitHub 一次性验证码", { exact: true }).waitFor();
  await page.evaluate(() => window.evolutionUI.finishLogin());
  await page.getByRole("region", { name: "贡献提交" }).waitFor();
  await page.getByRole("button", { name: "关闭", exact: true }).click();
  await page.waitForFunction(() => window.evolutionUI.activeReads === 0);
  await page.evaluate(() => { window.evolutionUI.holdState = true; });
  await page.getByRole("button", { name: "读取状态（测试）", exact: true }).click();
  await page.waitForFunction(() => Boolean(window.evolutionUI.finishState));
  await page.getByRole("button", { name: "发送新状态（测试）", exact: true }).click();
  await page.getByRole("alert").filter({ hasText: "新状态已经到达" }).waitFor();
  await page.evaluate(() => { window.evolutionUI.holdState = false; window.evolutionUI.finishState(); });
  await page.waitForTimeout(100);
  assert.equal(await page.getByRole("alert").filter({ hasText: "新状态已经到达" }).isVisible(), true, "An old status read replaced a newer event");
  assert.deepEqual(errors, []);
  console.log("PASS: focused evolution toolbar, automatic branch/PR/version reads, preserved drafts, branch readiness, serialized checks and explicit retry-safe submission");
} finally {
  await browser?.close(); await server.close();
  assert.equal(dirname(scratch), resolve(tmpdir()));
  await rm(scratch, { recursive: true, force: true });
}
