import assert from "node:assert/strict";
import { mkdtemp, rm, mkdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
import { chromium } from "playwright";
import { EvolutionAcceptance } from "../electron/evolution-acceptance.mjs";
import { EvolutionRequests } from "../electron/evolution-requests.mjs";

const ui = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const root = await mkdtemp(join(tmpdir(), "cleo-interaction-ui-"));
const server = await createServer({ root: ui, cacheDir: join(root, "vite-cache"), server: { host: "127.0.0.1", port: 0 } });
let browser;
try {
  await server.listen();
  browser = await chromium.launch({ executablePath: process.env.CLEO_TEST_BROWSER, headless: true });
  const page = await browser.newPage({ viewport: { width: 1200, height: 1000 } });
  page.setDefaultTimeout(10000);
  const errors = [];
  const output = join(process.env.CLEO_SMOKE_OUTPUT || join(ui, "output/playwright"), "interactions");
  await mkdir(output, { recursive: true });
  page.on("pageerror", (error) => errors.push(error.message));
  const state = { active: "new", candidate: "new", builds: [{ id: "new", kind: "local", sourceHash: "test" }] };
  const store = { root, read: async () => state, build: async () => state.builds[0] };
  const acceptance = new EvolutionAcceptance(store);
  const requests = new EvolutionRequests(acceptance, async (_thread, prompt) => {
    if (!prompt.includes("已完成一次集中确认")) return { intent: "clarification", answer: "入口放在侧栏还是设置页？" };
    return { intent: "change", answer: "假设：入口放在侧栏。", cases: [{ title: "入口位置", requirement: "move",
      current: "static only", trigger: "open sidebar", expectation: "在侧栏显示入口", evidence: "fixture:1" }] };
  });
  const original = await acceptance.create({ title: "入口位置", expectation: "原有入口可见", evidence: "操作：打开首页" });
  await acceptance.compare("new");
  await page.exposeFunction("fixtureSnapshot", async () => ({ acceptance: await acceptance.status(state), requests: await requests.status() }));
  await page.exposeFunction("fixtureAction", async (action, params) => {
    if (action === "feedback") return requests.feedback(params);
    if (action === "resume") { await requests.prepare(params); return acceptance.compare("new"); }
    if (action === "completeCase") return acceptance.complete(params.id, params.note);
    if (action === "compareCases") return acceptance.compare("new");
    throw new Error(`Unexpected action ${action}`);
  });
  await page.goto(`${server.resolvedUrls.local[0]}tests/interaction-fixture.html`);
  const input = page.getByTestId("composer-input");
  await input.fill("/"); assert.equal(await page.locator('[data-testid="slash-menu"] [role="option"]').count(), 5);
  await input.fill("/g"); assert.equal(await page.locator('[data-testid="slash-menu"] [role="option"]').count(), 3);
  await input.fill("/gri"); assert.equal(await page.locator('[data-testid="slash-menu"] [role="option"]').count(), 2);
  await page.getByTestId("composer").screenshot({ path: join(output, "skills.png") });
  await input.dispatchEvent("compositionstart");
  await input.dispatchEvent("keydown", { key: "Enter", code: "Enter", isComposing: true, keyCode: 229 });
  assert.equal(await input.inputValue(), "/gri");
  assert.equal(await page.getByTestId("sent").textContent(), "[]");
  await input.dispatchEvent("compositionend");
  await input.press("ArrowDown"); await input.press("Enter");
  assert.equal(await input.inputValue(), "/grilling ");
  assert.equal(await page.getByTestId("sent").textContent(), "[]");
  await input.fill("/grilling explain this plan"); await input.press("Enter");
  assert.match(await page.getByTestId("sent").textContent(), /grilling explain this plan/);
  await input.fill("/unmatched"); assert.equal(await page.locator('[data-testid="slash-menu"] [role="option"]').count(), 0);
  await input.fill("/gri"); await input.press("Backspace"); assert.equal(await page.locator('[data-testid="slash-menu"] [role="option"]').count(), 2);
  await page.getByRole("button", { name: "切换测试 harness" }).click();
  assert.equal(await page.locator('[data-testid="slash-menu"] [role="option"]').count(), 0);
  await input.fill("/"); assert.equal(await page.locator('[data-testid="slash-menu"] [role="option"]').count(), 3);
  await page.getByTestId("slash-menu").getByRole("option", { name: /claude-only/ }).click();
  assert.equal(await input.inputValue(), "/claude-only ");
  assert.ok(await input.evaluate((element) => element === document.activeElement));
  await page.getByRole("button", { name: "查看验收测试", exact: true }).click();
  await page.locator(".evolution-case-list > summary").click();
  assert.equal(await page.getByLabel("验收依据：入口位置", { exact: true }).count(), 0);
  assert.equal(await page.getByRole("button", { name: "验收", exact: true }).isEnabled(), true);
  assert.equal((await acceptance.interactions.read()).completions.length, 0);
  await page.getByLabel("继续反馈：入口位置", { exact: true }).fill("把入口移到另一个页面");
  await page.getByRole("button", { name: "继续修改：入口位置", exact: true }).click();
  await page.getByRole("button", { name: "跳过，按 Cleo 的判断继续", exact: true }).waitFor();
  assert.equal((await requests.status())[0].status, "clarification");
  assert.match(await page.getByRole("log").innerText(), /把入口移到另一个页面/);
  await page.getByRole("button", { name: "跳过，按 Cleo 的判断继续", exact: true }).click();
  await page.locator(".evolution-request dd").filter({ hasText: /^在侧栏显示入口$/ }).waitFor();
  assert.equal((await requests.suite()).find((c) => c.id === original.id).expectation, "原有入口可见");
  assert.equal((await acceptance.interactions.read()).confirmations[0].skipped, true);
  await page.getByLabel("继续反馈：入口位置", { exact: true }).scrollIntoViewIfNeeded();
  await page.locator(".evolution-cases").screenshot({ path: join(output, "feedback.png") });
  assert.equal(await page.getByLabel("验收依据：入口位置", { exact: true }).count(), 0);
  await page.getByRole("button", { name: "验收", exact: true }).click();
  await page.getByText(/0 项待验收/).waitFor();
  await page.reload(); await page.getByText(/0 项待验收/).waitFor();
  await page.getByRole("button", { name: "查看验收测试", exact: true }).click();
  assert.equal((await acceptance.interactions.read()).completions.length, 1);
  assert.equal((await acceptance.interactions.read()).completions[0].note, "");
  await acceptance.requirePassed("new");
  const feedbackCount = (await acceptance.interactions.read()).feedback.length;
  await acceptance.create({ title: "直接确认", expectation: "符合预期即可验收" });
  await acceptance.compare("new");
  await page.reload();
  await page.getByRole("button", { name: "查看验收测试", exact: true }).click();
  await page.locator(".evolution-case-list > summary").click();
  assert.equal(await page.getByLabel("继续反馈：直接确认", { exact: true }).inputValue(), "");
  assert.equal(await page.locator('textarea[aria-label^="验收依据"]').count(), 0);
  await page.getByRole("button", { name: "验收", exact: true }).click();
  await page.getByText(/0 项待验收/).waitFor();
  assert.equal((await acceptance.interactions.read()).feedback.length, feedbackCount);
  assert.equal((await acceptance.interactions.read()).completions.length, 2);
  assert.equal((await acceptance.interactions.read()).completions[1].note, "");
  await acceptance.requirePassed("new");
  assert.deepEqual(errors, []);
  await page.screenshot({ path: join(output, "completed.png"), fullPage: true });
  console.log("PASS: skills, feedback, skip, direct acceptance without notes or feedback, completion and reload (isolated fixtures)");
} finally {
  await browser?.close(); await server.close();
  assert.equal(dirname(root), resolve(tmpdir()));
  await rm(root, { recursive: true, force: true });
}
