/** Cleo's built-in browser: persistent tabs rendered as WebContentsViews in the main window.
 *
 * The user and the AI share the same WebContents. AI input and screenshots use the in-process
 * DevTools protocol (webContents.debugger), so no remote debugging port is opened, the real
 * mouse never moves and other applications keep keyboard focus. Coordinates exposed to callers
 * are view-relative device-independent pixels (the same pixels shown in the panel); page zoom is
 * converted to CSS pixels before dispatch.
 */

import { EventEmitter } from "node:events";
import { existsSync, mkdirSync } from "node:fs";
import { basename, extname, join } from "node:path";
import { MODIFIER_VK, modifierMask, parseShortcut } from "./keys.mjs";

const DEFAULT_SIZE = { width: 1280, height: 800 };
const NAVIGATION_SCHEMES = new Set(["http:", "https:", "cleo-file:"]);
const INPUT_TIMEOUT = 8000;
const MAX_NOTICES = 12;
const MAX_DOWNLOADS = 20;

const PERMISSION_LABELS = {
  media: "摄像头或麦克风", geolocation: "位置", notifications: "通知", midi: "MIDI 设备",
  midiSysex: "MIDI 设备", pointerLock: "锁定鼠标指针", fullscreen: "全屏", openExternal: "打开外部应用",
  "clipboard-read": "读取剪贴板", "idle-detection": "空闲检测", "display-capture": "屏幕共享",
  "window-management": "窗口管理", hid: "HID 设备", serial: "串口设备", usb: "USB 设备",
};

/** Purpose: Accept an address-bar entry. Input: user or AI text. Output: normalized http(s) URL. */
export function normalizeAddress(input) {
  const text = String(input ?? "").trim();
  if (!text) throw new Error("请输入网址。");
  if (text.length > 8192) throw new Error("网址过长。");
  if (/^about:blank$/i.test(text)) return "about:blank";
  let candidate = text;
  // "javascript:", "mailto:", "data:" and similar are schemes, not hosts; "localhost:3000" is a port.
  const scheme = /^([a-z][a-z\d+.-]*):(?!\d+(?:[/?#]|$))/i.exec(text);
  if (scheme && !/^[a-z][a-z\d+.-]*:\/\//i.test(text)) {
    throw new Error(`内置浏览器只打开 http、https 和工作区预览地址，不支持 ${scheme[1].toLowerCase()}:`);
  }
  if (!/^[a-z][a-z\d+.-]*:\/\//i.test(text)) {
    const local = /^(localhost|127(?:\.\d{1,3}){3}|\[::1\])(:\d+)?(?:[/?#]|$)/i.test(text);
    const hostLike = /^[^\s/?#]+\.[^\s/?#]+(?::\d+)?(?:[/?#]|$)/.test(text);
    if (!local && !hostLike) {
      return `https://www.bing.com/search?q=${encodeURIComponent(text)}`;
    }
    candidate = `${local ? "http" : "https"}://${text}`;
  }
  let url;
  try { url = new URL(candidate); } catch { throw new Error(`无法识别的网址：${text}`); }
  if (!NAVIGATION_SCHEMES.has(url.protocol)) {
    throw new Error(`内置浏览器只打开 http、https 和工作区预览地址，不支持 ${url.protocol}`);
  }
  if ((url.protocol === "http:" || url.protocol === "https:") && !url.hostname) throw new Error("网址缺少主机名。");
  return url.href;
}

function navigationAllowed(url) {
  if (url === "about:blank") return true;
  // blob: URLs are origin-bound documents generated by the page itself (previews, exports).
  try { const { protocol } = new URL(url); return NAVIGATION_SCHEMES.has(protocol) || protocol === "blob:"; } catch { return false; }
}

function withTimeout(promise, ms, message) {
  let timer;
  return Promise.race([
    promise.finally(() => clearTimeout(timer)),
    new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(message)), ms); }),
  ]);
}

/** Cancel a read-only wait without allowing a later result to reach the caller. */
function cancellable(promise, signal) {
  if (!signal) return promise;
  return new Promise((resolve, reject) => {
    const cancel = () => reject(signal.reason || new Error("工具调用已取消。"));
    signal.addEventListener("abort", cancel, { once: true });
    promise.then(resolve, reject).finally(() => signal.removeEventListener("abort", cancel));
    if (signal.aborted) cancel();
  });
}

const wait = ms => new Promise(resolve => setTimeout(resolve, ms));

function uniquePath(directory, name) {
  const safe = basename(String(name || "download")).replace(/[<>:"/\\|?*\x00-\x1f]/g, "_").slice(0, 160) || "download";
  const extension = extname(safe);
  const stem = safe.slice(0, safe.length - extension.length) || "download";
  let candidate = join(directory, safe);
  for (let index = 1; existsSync(candidate); index++) candidate = join(directory, `${stem} (${index})${extension}`);
  return candidate;
}

class Tab {
  constructor(id, view) {
    this.id = id;
    this.view = view;
    this.wc = view.webContents;
    this.error = null;
    this.crashed = null;
    this.unresponsive = false;
    this.dialog = null;
    this.fileChooser = null;
    this.pressed = new Set();
    this.dialogWaiters = new Set();
    this.attached = false;
    this.initialLoad = Promise.resolve();
    this.attachPromise = null;
    this.openerId = null;
  }
}

export class CleoBrowser extends EventEmitter {
  constructor({ electron, partition = "persist:cleo-browser", downloadsDir, overlay = null, platform = process.platform }) {
    super();
    this.electron = electron;
    this.partition = partition;
    this.downloadsDir = downloadsDir;
    this.overlayFiles = overlay;
    this.platform = platform;
    this.tabs = new Map();
    this.order = [];
    this.activeId = null;
    this.window = null;
    this.viewport = null;
    this.size = { ...DEFAULT_SIZE };
    this.geometry = 1;
    this.scale = 1;
    this.downloads = [];
    this.notices = [];
    this.nextTab = 1;
    this.overlayWanted = false;
    this.overlayView = null;
    this.keeper = null;
    // Views live in an off-screen keeper until a main window is attached and not minimized.
    this.parked = true;
    this.closed = false;
    this.configured = false;
    this.stateTimer = null;
  }

  /** Purpose: Configure the persistent profile once. Input: none. Output: Electron session. */
  session() {
    const ses = this.electron.session.fromPartition(this.partition);
    if (this.configured) return ses;
    this.configured = true;
    ses.setPermissionRequestHandler((wc, permission, callback) => {
      const allowed = permission === "clipboard-sanitized-write";
      callback(allowed);
      if (!allowed) this.notice(this.tabFor(wc), `网站请求“${PERMISSION_LABELS[permission] || permission}”权限，已拒绝。`);
    });
    ses.setPermissionCheckHandler((_wc, permission) => permission === "clipboard-sanitized-write");
    ses.setDevicePermissionHandler?.(() => false);
    // Remote pages must never read local files; workspace previews use the cleo-file scheme.
    ses.webRequest.onBeforeRequest({ urls: ["file://*/*"] }, (_details, callback) => callback({ cancel: true }));
    ses.on("will-download", (_event, item, wc) => this.download(item, wc));
    return ses;
  }

  attachWindow(window) {
    this.window = window;
    this.parkViews(window.isMinimized() || !window.isVisible());
    const repark = () => { if (!this.closed) this.parkViews(window.isMinimized() || !window.isVisible()); };
    window.on("minimize", repark);
    window.on("restore", repark);
    window.on("hide", repark);
    window.on("show", repark);
    window.once("closed", () => { this.window = null; this.parkViews(true); });
    this.scale = this.displayScale();
    const metrics = () => {
      const scale = this.displayScale();
      if (scale !== this.scale) { this.scale = scale; this.bump("display"); }
    };
    this.electron.screen.on("display-metrics-changed", metrics);
    window.on("moved", metrics);
    this.once("closed", () => this.electron.screen.removeListener("display-metrics-changed", metrics));
  }

  displayScale() {
    try {
      const bounds = this.window?.getBounds();
      return bounds ? this.electron.screen.getDisplayMatching(bounds).scaleFactor : 1;
    } catch { return 1; }
  }

  host() {
    if (this.parked || !this.window || this.window.isDestroyed()) return this.keeperWindow();
    return this.window;
  }

  keeperWindow() {
    if (this.keeper && !this.keeper.isDestroyed()) return this.keeper;
    // Chromium stops painting and screenshots in minimized windows. An inactive, off-screen,
    // non-focusable tool window keeps the same WebContents working without taking focus.
    this.keeper = new this.electron.BrowserWindow({
      show: false, x: -30000, y: -30000, width: this.size.width, height: this.size.height,
      frame: false, skipTaskbar: true, focusable: false, resizable: false,
      ...(this.platform === "win32" ? { type: "toolbar" } : {}),
      webPreferences: { sandbox: true, contextIsolation: true },
    });
    this.keeper.setIgnoreMouseEvents(true);
    this.keeper.showInactive();
    return this.keeper;
  }

  parkViews(parked) {
    if (this.closed) return;
    const keeperReady = Boolean(this.keeper) && !this.keeper.isDestroyed();
    if (parked && !this.tabs.size) {
      // Nothing to keep alive yet; the keeper is created when the first tab needs it.
      this.parked = true;
      return;
    }
    if (this.parked === parked && (!parked || keeperReady)) {
      this.layout();
      return;
    }
    const from = this.parked ? (keeperReady ? this.keeper : null) : this.window;
    this.parked = parked;
    const to = this.host();
    for (const tab of this.tabs.values()) {
      if (from && !from.isDestroyed()) from.contentView.removeChildView(tab.view);
      if (to && !to.isDestroyed()) to.contentView.addChildView(tab.view);
    }
    if (this.overlayView && this.window && !this.window.isDestroyed()) {
      this.window.contentView.removeChildView(this.overlayView);
      if (!parked) this.window.contentView.addChildView(this.overlayView);
    }
    this.layout();
  }

  /** Purpose: Place the active tab over the panel area. Input: DIP rect or null to hide. */
  setViewport(rect) {
    const next = rect && rect.width >= 40 && rect.height >= 40
      ? { x: Math.round(rect.x), y: Math.round(rect.y), width: Math.round(rect.width), height: Math.round(rect.height) }
      : null;
    this.viewport = next;
    if (next && (next.width !== this.size.width || next.height !== this.size.height)) {
      this.size = { width: next.width, height: next.height };
      this.bump("resize");
    }
    this.layout();
    this.emitState();
  }

  layout() {
    const showing = Boolean(this.viewport) && !this.parked;
    const origin = showing ? this.viewport : { x: 0, y: 0 };
    const bounds = { x: origin.x, y: origin.y, width: this.size.width, height: this.size.height };
    for (const tab of this.tabs.values()) {
      tab.view.setBounds(bounds);
      tab.view.setVisible(tab.id === this.activeId && (showing || this.parked));
    }
    if (this.parked && this.keeper && !this.keeper.isDestroyed()) {
      this.keeper.setBounds({ x: -30000, y: -30000, width: this.size.width, height: this.size.height });
    }
    this.layoutOverlay();
  }

  layoutOverlay() {
    const show = this.overlayWanted && Boolean(this.viewport) && !this.parked && Boolean(this.activeId);
    if (!show) { this.overlayView?.setVisible(false); return; }
    const overlay = this.overlay();
    if (!overlay) return;
    overlay.setBounds({ ...this.viewport, width: this.size.width, height: this.size.height });
    overlay.setVisible(true);
  }

  overlay() {
    if (this.overlayView || !this.overlayFiles || !this.window) return this.overlayView;
    this.overlayView = new this.electron.WebContentsView({ webPreferences: {
      sandbox: true, contextIsolation: true, nodeIntegration: false, preload: this.overlayFiles.preload,
    } });
    this.overlayView.setBackgroundColor("#00000000");
    void this.overlayView.webContents.loadFile(this.overlayFiles.html);
    this.window.contentView.addChildView(this.overlayView);
    return this.overlayView;
  }

  /** Purpose: Show "AI is operating, click to take over" above the page. Input: flag. */
  setAgentOverlay(wanted) {
    this.overlayWanted = Boolean(wanted);
    if (this.overlayWanted && this.overlayView && this.window && !this.parked) {
      // Keep the overlay above tabs created after it.
      this.window.contentView.removeChildView(this.overlayView);
      this.window.contentView.addChildView(this.overlayView);
    }
    this.layoutOverlay();
  }

  isOverlay(webContents) {
    return Boolean(this.overlayView) && webContents === this.overlayView.webContents;
  }

  bump(reason) {
    this.geometry += 1;
    this.emit("geometry", reason);
  }

  tabFor(webContents) {
    for (const tab of this.tabs.values()) if (tab.wc === webContents) return tab;
    return null;
  }

  requireTab(id) {
    const tab = this.tabs.get(String(id ?? ""));
    if (!tab || tab.wc.isDestroyed()) throw new Error(`标签页 ${id} 不存在或已关闭。请调用 browser_tabs 查看当前标签页。`);
    return tab;
  }

  activeTab() {
    return this.activeId ? this.requireTab(this.activeId) : null;
  }

  ensureTab() {
    return this.activeTab() || this.createTab();
  }

  /** Purpose: Open a tab. Input: optional URL, existing popup WebContents and focus flag. */
  createTab({ url = "", webContents = null, activate = true, openerId = null } = {}) {
    if (this.closed) throw new Error("内置浏览器已关闭。");
    const view = webContents
      ? new this.electron.WebContentsView({ webContents })
      : new this.electron.WebContentsView({ webPreferences: {
        session: this.session(), sandbox: true, contextIsolation: true, nodeIntegration: false,
        webSecurity: true, allowRunningInsecureContent: false, backgroundThrottling: false,
        spellcheck: false, safeDialogs: true, navigateOnDragDrop: false, webviewTag: false,
      } });
    view.setBackgroundColor("#ffffff");
    const tab = new Tab(`t${this.nextTab++}`, view);
    tab.openerId = openerId;
    this.tabs.set(tab.id, tab);
    this.order.push(tab.id);
    this.wire(tab);
    const attach = () => {
      if (!this.tabs.has(tab.id) || tab.wc.isDestroyed() || this.closed) return;
      this.host()?.contentView.addChildView(view);
      if (this.overlayView && this.window && !this.parked) {
        this.window.contentView.removeChildView(this.overlayView);
        this.window.contentView.addChildView(this.overlayView);
      }
      this.layout();
    };
    // Chromium focuses a new popup while it is created; attaching its view a moment later keeps
    // Cleo from being activated while the user works in another application.
    if (webContents) setTimeout(attach, 120); else attach();
    if (activate || !this.activeId) this.activeId = tab.id;
    this.layout();
    // A new WebContents has no renderer until its first navigation. The model must be able
    // to screenshot a fresh tab before navigating; existing popups already have a renderer.
    if (!webContents || url) {
      tab.initialLoad = this.load(tab, url || "about:blank").catch(error => {
        tab.error = { description: error.message, url }; this.emitState();
      });
    }
    this.emitState();
    this.emit("tabs");
    return tab;
  }

  wire(tab) {
    const { wc } = tab;
    wc.setWindowOpenHandler(({ url }) => {
      if (!navigationAllowed(url)) {
        this.notice(tab, `已阻止打开非网页地址：${String(url).slice(0, 120)}`);
        return { action: "deny" };
      }
      return {
        action: "allow",
        createWindow: options => this.createTab({ webContents: options.webContents, activate: true, openerId: tab.id }).wc,
      };
    });
    const guard = (event, url) => {
      if (navigationAllowed(url)) return;
      event.preventDefault();
      this.notice(tab, `已阻止跳转到非网页地址：${String(url).slice(0, 120)}`);
    };
    wc.on("will-navigate", guard);
    wc.on("will-redirect", guard);
    wc.on("will-attach-webview", event => event.preventDefault());
    wc.on("did-start-loading", () => { tab.error = null; this.emitState(); });
    for (const name of ["did-stop-loading", "page-title-updated", "did-navigate", "did-navigate-in-page", "page-favicon-updated"]) {
      wc.on(name, () => this.emitState());
    }
    wc.on("did-fail-load", (_event, code, description, url, isMainFrame) => {
      if (!isMainFrame || code === -3) return;
      tab.error = { code, description, url };
      this.emitState();
    });
    wc.on("render-process-gone", (_event, details) => {
      tab.crashed = details.reason || "crashed";
      tab.attached = false;
      tab.pressed.clear();
      tab.dialog = null;
      tab.fileChooser = null;
      this.emitState();
      this.emit("tab-crashed", tab.id);
    });
    wc.on("unresponsive", () => { tab.unresponsive = true; this.emitState(); });
    wc.on("responsive", () => { tab.unresponsive = false; this.emitState(); });
    wc.on("before-input-event", (event, input) => this.emit("user-input", { tab, event, input }));
    wc.on("destroyed", () => this.forget(tab));
  }

  /** Purpose: Attach the in-process DevTools client lazily. Input: tab. Output: ready tab. */
  async attach(tab) {
    if (tab.crashed) throw new Error(`标签页 ${tab.id} 已崩溃（${tab.crashed}）。请用 browser_history reload 重新加载。`);
    if (tab.attached) return tab;
    if (tab.attachPromise) return tab.attachPromise;
    const debug = tab.wc.debugger;
    tab.attachPromise = (async () => {
      try {
        await withTimeout((async () => {
          await tab.initialLoad;
          if (!debug.isAttached()) debug.attach("1.3");
          if (!tab.listening) {
            tab.listening = true;
            debug.on("message", (_event, method, params) => this.devtoolsEvent(tab, method, params));
            debug.on("detach", () => { tab.attached = false; });
          }
          await debug.sendCommand("Page.enable");
          await debug.sendCommand("DOM.enable");
          await debug.sendCommand("Emulation.setFocusEmulationEnabled", { enabled: true });
          await debug.sendCommand("Page.setInterceptFileChooserDialog", { enabled: true });
        })(), INPUT_TIMEOUT, "浏览器初始化超时。请重新加载标签页后重试。");
        tab.attached = true;
        return tab;
      } catch (error) {
        tab.attached = false;
        try { if (debug.isAttached()) debug.detach(); } catch { /* The renderer may already be gone. */ }
        throw error;
      } finally {
        tab.attachPromise = null;
      }
    })();
    return tab.attachPromise;
  }

  devtoolsEvent(tab, method, params) {
    if (method === "Page.javascriptDialogOpening") {
      tab.dialog = { type: params.type, message: String(params.message || "").slice(0, 2000),
        defaultPrompt: params.defaultPrompt || "", url: params.url };
      for (const resolve of tab.dialogWaiters) resolve();
      tab.dialogWaiters.clear();
      this.emitState();
    } else if (method === "Page.javascriptDialogClosed") {
      tab.dialog = null;
      this.emitState();
    } else if (method === "Page.fileChooserOpened") {
      tab.fileChooser = { backendNodeId: params.backendNodeId, mode: params.mode };
      this.emitState();
      this.emit("file-chooser", tab.id);
    }
  }

  command(tab, method, params = {}, timeout = INPUT_TIMEOUT) {
    return withTimeout(tab.wc.debugger.sendCommand(method, params), timeout, `浏览器操作超时（${method}）。页面可能无响应。`);
  }

  /** Dispatch input; if the page opens a JavaScript dialog the action stops without waiting. */
  async input(tab, method, params) {
    let onDialog;
    const dialog = new Promise(resolve => { onDialog = resolve; tab.dialogWaiters.add(resolve); });
    try {
      const outcome = await Promise.race([
        this.command(tab, method, params).then(() => "done"),
        dialog.then(() => "dialog"),
      ]);
      if (outcome === "dialog") throw Object.assign(new Error("页面弹出了对话框，操作暂停。"), { dialog: true });
    } finally {
      tab.dialogWaiters.delete(onDialog);
    }
  }

  cssPoint(tab, x, y) {
    const zoom = tab.wc.getZoomFactor() || 1;
    return { x: x / zoom, y: y / zoom };
  }

  async load(tab, input) {
    const url = input === "about:blank" ? input : normalizeAddress(input);
    tab.error = null;
    tab.crashed = null;
    const loaded = tab.wc.loadURL(url).catch(error => {
      if (!/ERR_ABORTED/.test(error.message)) tab.error = { description: error.message, url };
    });
    await Promise.race([loaded, wait(10000)]);
    this.emitState();
    return url;
  }

  async navigate(id, input) {
    return this.load(this.requireTab(id), input);
  }

  async history(id, action) {
    const tab = this.requireTab(id);
    const history = tab.wc.navigationHistory;
    if (action === "back") { if (!history.canGoBack()) throw new Error("没有可后退的页面。"); history.goBack(); }
    else if (action === "forward") { if (!history.canGoForward()) throw new Error("没有可前进的页面。"); history.goForward(); }
    else if (action === "reload") { tab.crashed = null; tab.error = null; tab.attached = false; tab.wc.reload(); }
    else if (action === "stop") tab.wc.stop();
    else throw new Error(`未知的浏览器历史操作：${action}`);
    await wait(action === "stop" ? 50 : 600);
    this.emitState();
  }

  activate(id) {
    const tab = this.requireTab(id);
    if (this.activeId !== tab.id) {
      this.activeId = tab.id;
      this.bump("tab");
    }
    this.layout();
    this.emitState();
    return tab;
  }

  close(id) {
    const tab = this.requireTab(id);
    tab.wc.close({ waitForBeforeUnload: false });
    this.forget(tab);
    if (!this.tabs.size && !this.closed) this.createTab({ url: "" });
  }

  forget(tab) {
    if (!this.tabs.has(tab.id)) return;
    this.tabs.delete(tab.id);
    this.order = this.order.filter(id => id !== tab.id);
    try { this.host()?.contentView.removeChildView(tab.view); } catch { /* Already detached. */ }
    try { if (tab.wc.debugger.isAttached()) tab.wc.debugger.detach(); } catch { /* Closed. */ }
    if (this.activeId === tab.id) {
      this.activeId = this.order.at(-1) || null;
      this.bump("tab");
    }
    this.layout();
    this.emitState();
    this.emit("tabs");
  }

  setZoom(id, factor) {
    const tab = this.requireTab(id);
    const next = Math.min(3, Math.max(0.3, Math.round(factor * 100) / 100));
    if (next !== tab.wc.getZoomFactor()) {
      tab.wc.setZoomFactor(next);
      this.bump("zoom");
    }
    this.emitState();
    return next;
  }

  /** Purpose: Capture exactly what the panel shows. Input: tab id. Output: DIP-sized PNG. */
  async capture(id, signal) {
    const tab = await cancellable(this.attach(this.requireTab(id)), signal);
    const { width, height } = this.size;
    if (tab.dialog) throw Object.assign(new Error("页面正在显示对话框。"), { dialog: true });
    const shot = await cancellable(this.command(tab, "Page.captureScreenshot", { format: "png" }, 15000), signal);
    let image = this.electron.nativeImage.createFromBuffer(Buffer.from(shot.data, "base64"));
    const device = image.getSize();
    if (device.width !== width || device.height !== height) {
      image = image.resize({ width, height, quality: "better" });
    }
    return { png: image.toPNG(), width, height, device, zoom: tab.wc.getZoomFactor(), scale: this.scale };
  }

  async click(id, x, y, { button = "left", clicks = 1 } = {}) {
    const tab = await this.attach(this.requireTab(id));
    const point = this.cssPoint(tab, x, y);
    await this.input(tab, "Input.dispatchMouseEvent", { type: "mouseMoved", ...point, button: "none", pointerType: "mouse" });
    const bit = { left: 1, right: 2, middle: 4 }[button];
    for (let count = 1; count <= clicks; count++) {
      tab.pressed.add(button);
      await this.input(tab, "Input.dispatchMouseEvent", { type: "mousePressed", ...point, button, buttons: bit, clickCount: count, pointerType: "mouse" });
      await this.input(tab, "Input.dispatchMouseEvent", { type: "mouseReleased", ...point, button, buttons: 0, clickCount: count, pointerType: "mouse" });
      tab.pressed.delete(button);
    }
  }

  async move(id, x, y) {
    const tab = await this.attach(this.requireTab(id));
    await this.input(tab, "Input.dispatchMouseEvent", { type: "mouseMoved", ...this.cssPoint(tab, x, y), button: "none", pointerType: "mouse" });
  }

  async drag(id, from, to, signal) {
    const tab = await this.attach(this.requireTab(id));
    const start = this.cssPoint(tab, from.x, from.y);
    const end = this.cssPoint(tab, to.x, to.y);
    await this.input(tab, "Input.dispatchMouseEvent", { type: "mouseMoved", ...start, button: "none", pointerType: "mouse" });
    tab.pressed.add("left");
    try {
      await this.input(tab, "Input.dispatchMouseEvent", { type: "mousePressed", ...start, button: "left", buttons: 1, clickCount: 1, pointerType: "mouse" });
      const steps = 12;
      for (let step = 1; step <= steps; step++) {
        signal?.throwIfAborted();
        const point = { x: start.x + (end.x - start.x) * step / steps, y: start.y + (end.y - start.y) * step / steps };
        await this.input(tab, "Input.dispatchMouseEvent", { type: "mouseMoved", ...point, button: "left", buttons: 1, pointerType: "mouse" });
        await wait(16);
      }
      await this.input(tab, "Input.dispatchMouseEvent", { type: "mouseReleased", ...end, button: "left", buttons: 0, clickCount: 1, pointerType: "mouse" });
      tab.pressed.delete("left");
    } finally {
      if (tab.pressed.has("left")) await this.releaseInputs(tab.id).catch(() => {});
    }
  }

  async scroll(id, x, y, deltaX, deltaY) {
    const tab = await this.attach(this.requireTab(id));
    const point = this.cssPoint(tab, x, y);
    await this.input(tab, "Input.dispatchMouseEvent", { type: "mouseMoved", ...point, button: "none", pointerType: "mouse" });
    await this.input(tab, "Input.dispatchMouseEvent", { type: "mouseWheel", ...point, deltaX, deltaY, pointerType: "mouse" });
    await wait(250);
  }

  async type(id, text, signal) {
    const tab = await this.attach(this.requireTab(id));
    const lines = String(text).split(/\r?\n/);
    for (let index = 0; index < lines.length; index++) {
      signal?.throwIfAborted();
      if (index) await this.press(tab, parseShortcut("Enter"));
      // insertText reaches the focused element without key events; long text is chunked so
      // stop requests take effect between chunks.
      for (let offset = 0; offset < lines[index].length; offset += 500) {
        signal?.throwIfAborted();
        await this.input(tab, "Input.insertText", { text: lines[index].slice(offset, offset + 500) });
      }
    }
  }

  async keys(id, shortcut) {
    const tab = await this.attach(this.requireTab(id));
    await this.press(tab, parseShortcut(shortcut));
  }

  async press(tab, { modifiers, key }) {
    let mask = 0;
    const down = [];
    try {
      for (const name of modifiers) {
        mask |= modifierMask([name]);
        down.push(name);
        tab.pressed.add(`key:${name}`);
        await this.input(tab, "Input.dispatchKeyEvent", { type: "rawKeyDown", key: name, code: `${name}Left`, windowsVirtualKeyCode: MODIFIER_VK[name], modifiers: mask });
      }
      if (key) {
        const printable = key.text && !(mask & ~modifierMask(["Shift"]));
        const text = printable ? (mask & modifierMask(["Shift"]) ? key.text.toUpperCase() : key.text) : "";
        const keyName = key.key.length === 1 && (mask & modifierMask(["Shift"])) ? key.key.toUpperCase() : key.key;
        await this.input(tab, "Input.dispatchKeyEvent", { type: text ? "keyDown" : "rawKeyDown", key: keyName, code: key.code,
          windowsVirtualKeyCode: key.keyCode, modifiers: mask, ...(text ? { text, unmodifiedText: key.text } : {}) });
        await this.input(tab, "Input.dispatchKeyEvent", { type: "keyUp", key: keyName, code: key.code, windowsVirtualKeyCode: key.keyCode, modifiers: mask });
      }
    } finally {
      for (const name of down.reverse()) {
        mask &= ~modifierMask([name]);
        await this.command(tab, "Input.dispatchKeyEvent", { type: "keyUp", key: name, code: `${name}Left`, windowsVirtualKeyCode: MODIFIER_VK[name], modifiers: mask }, 2000).catch(() => {});
        tab.pressed.delete(`key:${name}`);
      }
    }
  }

  /** Purpose: Release mouse buttons and modifiers an interrupted AI action left pressed. */
  async releaseInputs(id) {
    const tab = this.tabs.get(id);
    if (!tab || !tab.attached || tab.wc.isDestroyed()) return [];
    const released = [];
    for (const item of [...tab.pressed]) {
      if (item.startsWith("key:")) {
        const name = item.slice(4);
        await this.command(tab, "Input.dispatchKeyEvent", { type: "keyUp", key: name, code: `${name}Left`, windowsVirtualKeyCode: MODIFIER_VK[name], modifiers: 0 }, 2000).catch(() => {});
      } else {
        await this.command(tab, "Input.dispatchMouseEvent", { type: "mouseReleased", x: 0, y: 0, button: item, buttons: 0, clickCount: 1 }, 2000).catch(() => {});
      }
      tab.pressed.delete(item);
      released.push(item);
    }
    return released;
  }

  async releaseAll() {
    const released = [];
    for (const id of this.tabs.keys()) released.push(...await this.releaseInputs(id));
    return released;
  }

  async handleDialog(id, accept, promptText = "") {
    const tab = await this.attach(this.requireTab(id));
    if (!tab.dialog) throw new Error("当前标签页没有打开的对话框。");
    await this.command(tab, "Page.handleJavaScriptDialog", { accept: Boolean(accept), ...(promptText ? { promptText: String(promptText).slice(0, 2000) } : {}) });
    tab.dialog = null;
    this.emitState();
  }

  async setFiles(id, paths) {
    const tab = await this.attach(this.requireTab(id));
    if (!tab.fileChooser) throw new Error("当前标签页没有等待中的文件选择框。请先点击网页中的上传按钮。");
    if (tab.fileChooser.mode === "selectSingle" && paths.length > 1) throw new Error("该文件选择框只接受一个文件。");
    await this.command(tab, "DOM.setFileInputFiles", { files: paths, backendNodeId: tab.fileChooser.backendNodeId });
    tab.fileChooser = null;
    this.emitState();
  }

  cancelFileChooser(id) {
    const tab = this.requireTab(id);
    tab.fileChooser = null;
    this.emitState();
  }

  async pageText(id, limit = 6000) {
    const tab = await this.attach(this.requireTab(id));
    const zoom = tab.wc.getZoomFactor() || 1;
    const script = `(() => {
      const text = (document.body?.innerText || "").replace(/\\n{3,}/g, "\\n\\n").slice(0, ${Math.max(500, Math.min(limit, 20000))});
      const selector = 'a[href],button,input,select,textarea,[role=button],[role=link],[contenteditable=true],summary';
      const items = [];
      for (const element of document.querySelectorAll(selector)) {
        const box = element.getBoundingClientRect();
        if (box.width < 2 || box.height < 2 || box.bottom < 0 || box.right < 0 || box.top > innerHeight || box.left > innerWidth) continue;
        const style = getComputedStyle(element);
        if (style.visibility === "hidden" || style.display === "none") continue;
        const label = (element.getAttribute("aria-label") || element.innerText || element.value || element.placeholder || element.title || element.name || "").trim().replace(/\\s+/g, " ").slice(0, 80);
        items.push({ tag: element.tagName.toLowerCase(), type: element.type || "", label,
          x: Math.round((box.left + box.width / 2) * ${zoom}), y: Math.round((box.top + box.height / 2) * ${zoom}) });
        if (items.length >= 80) break;
      }
      return { title: document.title, text, elements: items };
    })()`;
    const result = await this.command(tab, "Runtime.evaluate", { expression: script, returnByValue: true, awaitPromise: false }, 10000);
    if (result.exceptionDetails) throw new Error("无法读取页面内容。");
    return result.result.value;
  }

  download(item, webContents) {
    const tab = this.tabFor(webContents);
    mkdirSync(this.downloadsDir, { recursive: true });
    const path = uniquePath(this.downloadsDir, item.getFilename());
    item.setSavePath(path);
    const record = { id: `d${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`, name: basename(path), path,
      url: item.getURL().slice(0, 500), state: "progressing", received: 0, total: item.getTotalBytes(), tabId: tab?.id || null };
    this.downloads.unshift(record);
    this.downloads.length = Math.min(this.downloads.length, MAX_DOWNLOADS);
    item.on("updated", (_event, state) => {
      record.state = state === "interrupted" ? "interrupted" : "progressing";
      record.received = item.getReceivedBytes();
      record.total = item.getTotalBytes();
      this.emitState();
    });
    item.once("done", (_event, state) => {
      record.state = state;
      record.received = item.getReceivedBytes();
      this.notice(tab, state === "completed" ? `下载完成：${record.name}` : `下载未完成（${state}）：${record.name}`);
      this.emitState();
    });
    this.emitState();
  }

  notice(tab, text) {
    this.notices.unshift({ at: Date.now(), tabId: tab?.id || null, text: String(text).slice(0, 300) });
    this.notices.length = Math.min(this.notices.length, MAX_NOTICES);
    this.emitState();
  }

  tabState(tab) {
    const { wc } = tab;
    const destroyed = wc.isDestroyed();
    return {
      id: tab.id,
      title: destroyed ? "" : wc.getTitle(),
      url: destroyed ? "" : wc.getURL(),
      loading: !destroyed && wc.isLoading(),
      canGoBack: !destroyed && wc.navigationHistory.canGoBack(),
      canGoForward: !destroyed && wc.navigationHistory.canGoForward(),
      zoom: destroyed ? 1 : wc.getZoomFactor(),
      crashed: tab.crashed,
      unresponsive: tab.unresponsive,
      error: tab.error,
      dialog: tab.dialog && { type: tab.dialog.type, message: tab.dialog.message, defaultPrompt: tab.dialog.defaultPrompt },
      fileChooser: tab.fileChooser && { mode: tab.fileChooser.mode },
    };
  }

  state() {
    return {
      tabs: this.order.map(id => this.tabs.get(id)).filter(Boolean).map(tab => this.tabState(tab)),
      activeTabId: this.activeId,
      size: this.size,
      visible: Boolean(this.viewport),
      parked: this.parked,
      downloads: this.downloads.map(item => ({ ...item })),
      notices: this.notices.slice(0, 6),
      downloadsDir: this.downloadsDir,
    };
  }

  emitState() {
    if (this.stateTimer) return;
    this.stateTimer = setTimeout(() => { this.stateTimer = null; this.emit("state", this.state()); }, 40);
  }

  /** Purpose: Release every tab and window at exit (distinct from closing one tab). */
  async shutdown() {
    this.closed = true;
    clearTimeout(this.stateTimer);
    await this.releaseAll().catch(() => {});
    // Persist logins even if the process exits right after closing.
    if (this.configured) await this.session().cookies.flushStore().catch(() => {});
    for (const tab of [...this.tabs.values()]) {
      try { if (tab.wc.debugger.isAttached()) tab.wc.debugger.detach(); } catch { /* Closing. */ }
      try { tab.wc.close({ waitForBeforeUnload: false }); } catch { /* Closing. */ }
    }
    this.tabs.clear();
    this.order = [];
    try { this.overlayView?.webContents.close(); } catch { /* Closing. */ }
    if (this.keeper && !this.keeper.isDestroyed()) this.keeper.destroy();
    this.emit("closed");
  }
}
