from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PYPROJECT_PATH = PROJECT_ROOT / "pyproject.toml"
REQUIREMENTS_PATH = PROJECT_ROOT / "requirements.txt"
RESOLVER_DOCKERFILE = PROJECT_ROOT / "docker" / "requirements.Dockerfile"
RESOLVER_IMAGE = "cleo-dependency-resolver:local"
RESOLVER_CACHE_VOLUME = "cleo-uv-cache"
DEFAULT_INDEX_URL = os.environ.get("CLEO_PYPI_INDEX_URL", "https://pypi.org/simple")
DEFAULT_EXTRA_INDEX_URL = os.environ.get("CLEO_PYPI_EXTRA_INDEX_URL", "")


def _run(command: list[str]) -> None:
    print(f"+ {subprocess.list2cmdline(command)}", flush=True)
    subprocess.run(command, cwd=PROJECT_ROOT, check=True)


def _validate_pyproject() -> None:
    with PYPROJECT_PATH.open("rb") as file:
        config = tomllib.load(file)

    project = config.get("project")
    if not isinstance(project, dict):
        raise RuntimeError("pyproject.toml does not contain a [project] table")

    dependencies = project.get("dependencies")
    if not isinstance(dependencies, list) or not dependencies:
        raise RuntimeError("pyproject.toml must contain a non-empty project.dependencies list")

    invalid = [item for item in dependencies if not isinstance(item, str) or not item.strip()]
    if invalid:
        raise RuntimeError("pyproject.toml contains an invalid dependency entry")

    print(
        f"Validated {len(dependencies)} direct dependencies from "
        f"{PYPROJECT_PATH.name}.",
        flush=True,
    )


def _check_docker() -> None:
    if shutil.which("docker") is None:
        raise RuntimeError("Docker CLI was not found on PATH")
    _run(["docker", "version", "--format", "{{.Server.Version}}"])


def _normalized_requirements(generated_path: Path) -> str:
    generated = generated_path.read_text(encoding="utf-8").replace("\r\n", "\n")
    generated = generated.lstrip()
    if not generated:
        raise RuntimeError("dependency resolver generated an empty requirements file")
    if "-e ." in generated or "file:///" in generated:
        raise RuntimeError("generated requirements unexpectedly contain a local project path")

    header = (
        "# Generated from pyproject.toml by scripts/update_project.py.\n"
        "# Do not edit this file manually.\n"
    )
    return f"{header}{generated.rstrip()}\n"


def _build_resolver_image(index_url: str, extra_index_url: str) -> None:
    command = [
        "docker",
        "build",
        "--file",
        str(RESOLVER_DOCKERFILE),
        "--tag",
        RESOLVER_IMAGE,
        "--build-arg",
        f"PIP_INDEX_URL={index_url}",
    ]
    if extra_index_url:
        command.extend(["--build-arg", f"PIP_EXTRA_INDEX_URL={extra_index_url}"])
    command.append(".")
    _run(command)


def _compile_requirements(
    *,
    check_only: bool,
    index_url: str,
    extra_index_url: str,
) -> bool:
    with tempfile.TemporaryDirectory(prefix="cleo-dependencies-") as output_dir:
        output_path = Path(output_dir) / "requirements.txt"
        command = [
            "docker",
            "run",
            "--rm",
            "--mount",
            f"type=bind,source={PROJECT_ROOT},target=/src,readonly",
            "--mount",
            f"type=bind,source={output_dir},target=/out",
            "--mount",
            f"type=volume,source={RESOLVER_CACHE_VOLUME},target=/root/.cache/uv",
        ]
        if extra_index_url:
            # uv searches UV_INDEX first and uses UV_DEFAULT_INDEX as the fallback.
            command.extend(["--env", f"UV_INDEX={index_url}"])
            command.extend(["--env", f"UV_DEFAULT_INDEX={extra_index_url}"])
        else:
            command.extend(["--env", f"UV_DEFAULT_INDEX={index_url}"])
        command.extend(
            [
                "--workdir",
                "/src",
                RESOLVER_IMAGE,
                "pip",
                "compile",
                "--upgrade",
                "--strip-extras",
                "--no-header",
                "--no-annotate",
                "--no-emit-index-url",
                "--output-file=/out/requirements.txt",
                "/src/pyproject.toml",
            ]
        )
        _run(command)
        generated = _normalized_requirements(output_path)

    current = (
        REQUIREMENTS_PATH.read_text(encoding="utf-8").replace("\r\n", "\n")
        if REQUIREMENTS_PATH.exists()
        else ""
    )
    changed = current != generated

    if check_only:
        if changed:
            print("requirements.txt is out of date.", file=sys.stderr)
        else:
            print("requirements.txt is up to date.")
        return changed

    if changed:
        temporary_path = REQUIREMENTS_PATH.with_suffix(".txt.tmp")
        temporary_path.write_text(generated, encoding="utf-8", newline="\n")
        temporary_path.replace(REQUIREMENTS_PATH)
        print("Updated requirements.txt.")
    else:
        print("requirements.txt was already up to date.")
    return False


def _build_image(index_url: str, extra_index_url: str, *, pull: bool) -> None:
    command = [
        "docker",
        "compose",
        "build",
    ]
    if pull:
        command.append("--pull")
    command.extend(["--build-arg", f"PIP_INDEX_URL={index_url}"])
    if extra_index_url:
        command.extend(["--build-arg", f"PIP_EXTRA_INDEX_URL={extra_index_url}"])
    _run(command)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Regenerate requirements.txt from pyproject.toml in a Python 3.12 "
            "Linux container and rebuild the Cleo Docker image."
        )
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Update requirements.txt without rebuilding the Docker image.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit with status 1 when requirements.txt is stale; do not modify files or build.",
    )
    parser.add_argument(
        "--pull",
        action="store_true",
        help="Refresh base images before building instead of using the local Docker cache.",
    )
    parser.add_argument(
        "--index-url",
        default=DEFAULT_INDEX_URL,
        help=(
            "Python package index used by uv and Docker builds. Defaults to "
            "CLEO_PYPI_INDEX_URL or https://pypi.org/simple."
        ),
    )
    parser.add_argument(
        "--extra-index-url",
        default=DEFAULT_EXTRA_INDEX_URL,
        help=(
            "Fallback package index for packages missing from --index-url. "
            "Defaults to CLEO_PYPI_EXTRA_INDEX_URL."
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    try:
        _validate_pyproject()
        _check_docker()
        _build_resolver_image(args.index_url, args.extra_index_url)
        stale = _compile_requirements(
            check_only=args.check,
            index_url=args.index_url,
            extra_index_url=args.extra_index_url,
        )
        if args.check:
            return 1 if stale else 0
        if not args.skip_build:
            _build_image(args.index_url, args.extra_index_url, pull=args.pull)
    except (OSError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"Update failed: {exc}", file=sys.stderr)
        return 1

    print("Dependency lock and Docker image are ready.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
